version: '3.8'
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:2023.3
    restart: unless-stopped
    volumes:
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Europe/Berlin
    ports:
      - 8123:8123
    networks:
      default:
      mqtt:
        ipv4_address: 172.20.0.3
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt-mosquitto
    restart: unless-stopped
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    ports:
      - 1883:1883
    networks:
      mqtt:
        ipv4_address: 172.20.0.2

networks:
  mqtt:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
